version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ..:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        build:
            context: .
        image: ascio-php
        volumes:
            - ..:/code
            - c:/path/to/ascio.json:/path/to/ascio.json